/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hmangala' at '1/8/16 9:27 PM' with Gradle 2.14
 *
 * @author hmangala, @date 1/8/16 9:27 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
